# Generated by Django 3.1.7 on 2021-03-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_role',
            field=models.CharField(choices=[('USER', 'User'), ('OWNER', 'Owner'), ('ADMIN', 'Admin')], max_length=10),
        ),
    ]
