# Generated by Django 3.1.7 on 2021-03-31 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_verificationtokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
    ]
