# Generated by Django 3.1.7 on 2021-04-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtokens',
            name='token',
            field=models.CharField(max_length=6),
        ),
    ]
