# Generated by Django 3.1.7 on 2021-03-17 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Futsal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('futsal_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phn_number', models.CharField(max_length=20)),
                ('fut_type', models.CharField(choices=[('7A', '7A'), ('5A', '5A')], max_length=2)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('contact_email', models.EmailField(max_length=254, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
