# Generated by Django 3.1.7 on 2021-03-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0003_auto_20210322_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_book_date', models.DateField()),
                ('user_book_time', models.TimeField()),
                ('user_book_fut_type', models.CharField(choices=[('7A', '7A'), ('5A', '5A')], max_length=2)),
            ],
        ),
    ]
