# Generated by Django 3.1.7 on 2021-03-22 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0005_userbooking_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='futsal',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='futsal.futsal'),
            preserve_default=False,
        ),
    ]
