# Generated by Django 3.1.7 on 2021-03-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0006_userbooking_futsal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('discount', models.PositiveIntegerField()),
                ('futsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futsal.futsal')),
            ],
        ),
    ]
