# Generated by Django 3.1.7 on 2021-03-24 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0007_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='weekday',
            field=models.CharField(choices=[('SUN', 'SUN'), ('MON', 'MON'), ('TUE', 'TUE'), ('THU', 'THU'), ('WED', 'WED')], default='SUN', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='weekend_days',
            field=models.CharField(choices=[('FRI', 'FRI'), ('SAT', 'SAT')], default='SAT', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='futsal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslot', to='futsal.futsal'),
        ),
    ]
