# Generated by Django 3.1.7 on 2021-03-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0008_auto_20210324_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('t_date', models.CharField(max_length=100)),
                ('t_location', models.CharField(max_length=100)),
                ('t_price', models.PositiveIntegerField()),
                ('t_age', models.CharField(max_length=100)),
                ('t_sessions', models.CharField(max_length=200)),
                ('t_photo', models.ImageField(upload_to='')),
                ('t_contact_phone', models.CharField(max_length=200)),
                ('t_email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='weekday',
            field=models.CharField(choices=[('SUN', 'SUN'), ('MON', 'MON'), ('TUE', 'TUE'), ('THU', 'THU'), ('WED', 'WED')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='weekend_days',
            field=models.CharField(choices=[('FRI', 'FRI'), ('SAT', 'SAT')], max_length=3, null=True),
        ),
    ]
