# Generated by Django 3.1.7 on 2021-03-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0010_auto_20210325_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='address',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='email',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='name',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='phone',
        ),
        migrations.AddField(
            model_name='membership',
            name='member_type',
            field=models.CharField(choices=[('1 month (Rs 200)', '1 month (Rs 200)'), ('2 month (Rs 400)', '2 month (Rs 400)'), ('3 month (Rs 500)', '3 month (Rs 500)')], default='1 month (Rs 200)', max_length=20),
            preserve_default=False,
        ),
    ]
