# Generated by Django 3.1.7 on 2021-03-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0011_auto_20210325_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='weekday',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='weekend_days',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default='2011-12-09'),
            preserve_default=False,
        ),
    ]
