# Generated by Django 3.1.7 on 2021-03-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0012_auto_20210325_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
