# Generated by Django 3.1.7 on 2021-03-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0013_delete_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
    ]
