# Generated by Django 3.1.7 on 2021-03-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0014_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
