# Generated by Django 3.1.7 on 2021-03-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0015_delete_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futsal',
            name='phn_number',
        ),
        migrations.AlterField(
            model_name='membership',
            name='member_type',
            field=models.CharField(choices=[('1 month ', 'Rs 200'), ('2 month ', 'Rs 400'), ('3 month ', 'Rs 500')], max_length=20),
        ),
    ]
