# Generated by Django 3.1.7 on 2021-03-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0016_auto_20210329_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member_type',
            field=models.CharField(choices=[('Gold ', 'Gold'), ('Platinum ', 'Platinum'), ('Diamond ', 'Diamond')], max_length=20),
        ),
    ]
