# Generated by Django 3.1.7 on 2021-03-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0019_auto_20210330_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooking',
            name='user_book_fut_type',
            field=models.CharField(choices=[('7A', '7A'), ('5A', '5A'), ('5A/7A', '5A/7A')], max_length=7),
        ),
    ]
