# Generated by Django 3.1.7 on 2021-03-31 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0020_auto_20210330_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='pay_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
