# Generated by Django 3.1.7 on 2021-04-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0021_membership_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainings',
            name='t_photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
