# Generated by Django 3.1.7 on 2021-04-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0022_auto_20210402_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainings',
            name='t_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
