# Generated by Django 3.1.7 on 2021-04-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0023_auto_20210402_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futsal',
            name='fut_type',
            field=models.CharField(choices=[('7A', '7A'), ('5A', '5A'), ('5A/7A', '5A/7A')], max_length=10),
        ),
    ]
