# Generated by Django 3.1.7 on 2021-04-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0025_futsal_fut_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourno_photo', models.ImageField(null=True, upload_to='')),
                ('tourno_name', models.CharField(max_length=100)),
                ('tourno_location', models.CharField(max_length=100)),
                ('tourno_date', models.CharField(max_length=200)),
            ],
        ),
    ]
