# Generated by Django 3.1.7 on 2021-04-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0026_tournaments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournaments',
            name='tourno_photo',
        ),
    ]
