# Generated by Django 3.1.7 on 2021-04-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0028_auto_20210405_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='tourno_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
